### ISSUE TITLE
List of past year projects' websites for reference

### ISSUE THREAD

**Issue by paekva** [Ovaday/DEEMa#29]
Make list of past year projects: * pros and cons * 
One person makes a list, everybody reviews and writes the summary why he likes or don't. 
Further discuss.

**Comment by paekva** [comment]
### 2021

> **Smart home**
> 1. https://techphantoms.de/
> 2. https://infinite-team.com/ 
> 3. https://patelshyam.github.io/Aeros/ 
> 
> **Research data management**
> 1. http://daino.eu/ 
> 2. https://techfour.de/ 
> 3. https://codeedit.de/


### 2020

> **Microservices**
> 1. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/exemplarische.github.io/home/ 
> 2. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/nullx-de.github.io/home/ 
> 3. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/super-team.eu/
> 
> **Blockchain**
> 1. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/bitbricks.tech/ 
> 2. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/ltsquare-global.web.app/ 
> 3. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/triwotech.de/
> 
> **SmartRail**
> 1. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/adm-tech.de/ 
> 2. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/eveloperz.com/ 
> 3. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/seaquasar.de/
> 
>  **Research data management**
> 1. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/spectre-x.de/ 
> 2. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/wirtrials.web.app/ 
> 3. https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/zap.com.de/ 


### 2019

> **Press Application**
> 1. https://vsr.informatik.tu-chemnitz.de/edu/2019/planspiel/results/binuv.com/
> 2. https://vsr.informatik.tu-chemnitz.de/edu/2019/planspiel/results/www.fiveberg.de/ 
> 3. https://vsr.informatik.tu-chemnitz.de/edu/2019/planspiel/results/techtians.com/ 
> 4. https://vsr.informatik.tu-chemnitz.de/edu/2019/planspiel/results/upfives.com/ 
> 
> **Blockchain**
> 1. https://vsr.informatik.tu-chemnitz.de/edu/2019/planspiel/results/ctustech.com/ 
> 2. https://vsr.informatik.tu-chemnitz.de/edu/2019/planspiel/results/pentastreams.com/ 
> 3. https://vsr.informatik.tu-chemnitz.de/edu/2019/planspiel/results/techmarkable.com/
> 
> **Robotics**
> 1. https://vsr.informatik.tu-chemnitz.de/edu/2019/planspiel/results/robo-werk.com/ 
> 2. https://vsr.informatik.tu-chemnitz.de/edu/2019/planspiel/results/robium-automations.com/ 
> 3. https://vsr.informatik.tu-chemnitz.de/edu/2019/planspiel/results/thinkbots.tech/
>

**Comment by Nikvasil** [comment]
https://techphantoms.de/

**Pros:**

- Sticky header
- Responsible icons 
- Centralized content (sides padding)

**Cons:**

- Logo and website colors don't match
- Logo is overloaded

https://infinite-team.com/

**Pros:**

- Sticky header

**Cons:**

- Wide header (it literally takes 1/5 of my monitor) 
- Too much text (Our Product paragraph)

https://patelshyam.github.io/Aeros/

**Pros:**

- Logo match with website colors

**Cons:**

- About us paragraph looks strange (I think they should have aligned team culture columns and put them in a row)
- Transparent header (it conflicts with the website content text)

http://daino.eu/

**Pros:**

- I like the way they have designed team culture (3 equal rects + values tree)

**Cons:**

- Maybe youtube videos are not really necessary 

https://techfour.de/

**Pros:**

- I liked that all the pictures are from one family

**Cons:**

- Border shadows are almost invisible on hover (Our Values paragraph)

https://codeedit.de/

**Pros:**

- Values tree

**Cons:**

- Bulding logo

**Comment by sunny-26** [comment]
https://techphantoms.de/

Pros:

Fixed header
Adaptable depending on page size content
only 3 colors have been used
Portfolio (We can do our services part) and write all things that we can do
Cons:

Logo and website colors don't match
Logo is overloaded
https://infinite-team.com/

Pros:

Sticky header
Animation, although in my point of view, it is too much, a bit annoying.
Cons:

Too Wide header =should be changeable depending on the page size
Too much text (Our Product paragraph)

Subscription option
Nothing that tels you that it is a project not a real startup.
https://patelshyam.github.io/Aeros/

Pros:

Logo colors look good
Map (we can add it as a link to google in the address section, for example)
The icon can return us to the beginning of the page
Cons:
Orange color sometimes
Animation 
Too much text
Nothing that tels you that it is a project not a real startup.
http://daino.eu/

Pros:


Cons:

cant open

https://techfour.de/

Pros:

Pictures are all in the same style
Cons:

the Map is too big.
too much info.
Sign up bottom is not aligned with enter email field.
Nothing that tels you that it is a project not a real startup.
https://codeedit.de/

Pros:

Values tree (we can use something simmilar)
The size of the menu bar
Disclaimer
Cons:

 logo

Text Color on the banner.

https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/exemplarische.github.io/home/
Pros:
The icon to return to the beginning of the page
Disclaimer(kind of)
Cons:
colors, text colors
Logo
Avocado

https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/nullx-de.github.io/home/

Pros:
Pictures
Values are reacted on hover
Icon 
Animation, although i dont like it.
Cons:
Learn more button is overflowing when the page is not on the full size
too 
Links(buttons would look much better)

https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/super-team.eu/

Pros:
Logo
Down arrow
Animation

Team skills section
Cons:
Text style
Some stuff is not good aligned with each other
Animation
No disclaimer
Colors

Arrows(?)

https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/bitbricks.tech/

Pros:
Logo
Survey
Contact us form
Cons:

Colors
Fonts
Disclaimer at the very end of the page

https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/ltsquare-global.web.app/

Pros:
Logo with slogan
Colors
Map
Cons:
photos are not aligned with the text, photos qulity
fonts, text style in general
strange icons for values - well there are undestendable, but with textual description would be much better
Disclaimer at the end

https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/triwotech.de/

Pros: 
animated banner 
Advantages of using blockchain, we can do the same with data management
On hover

Cons:
photo
Colors(blue with dark blue)


https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/adm-tech.de/

Pros:
Logo
Map
Cons:
Menu is transparent
Fonts
Colors
List with numbers
Text is not adjustable when the page size is different from the full screen
Ticktock link in the footer


https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/eveloperz.com/

Pros:
colors
animation
Cons:
too much text
Picture with values 
Disclaimer is only at the end



https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/seaquasar.de/


Pros:
Good moto
on hover sevices and values

Cons:
arrow
All sections are styled differently - doesnt look like the same page

Disclaimer at the end
colors



https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/spectre-x.de/
Pros:
disclaimer
statistics
our workspace section
Cons>:
colors
principles 

https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/wirtrials.web.app/

Pros:

Disclaimer
Logo
Animation
Cons:
Values picture
Alignement sometimes


https://vsr.informatik.tu-chemnitz.de/edu/2020/planspiel/results/zap.com.de/


Pros:
Logo
colors
Map
Transparent menu
Cons:
disclaimer
Banner part(doesnt give the understanding of what they do)

**Comment by paekva** [comment]
Please, add your observation to the table (link in the dialog)

**Comment by mraxemax** [comment]
In this website https://codeedit.de/ i like the team member view.

![image](https://user-images.githubusercontent.com/26617338/200169128-4edc4169-4d9c-451a-b582-610db16a497a.png)

In this website https://techfour.de/ i like the map.
<img width="1628" alt="image" src="https://user-images.githubusercontent.com/26617338/200169215-aec74c0e-2a3d-489f-ba9a-b04c248c91e4.png">

**Comment by mraxemax** [comment]
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/26617338/200169314-a03f028f-dae1-4033-8515-b75215cb4765.png">
